--> statement-breakpoint

-- CUSTOM: Create application roles for RLS enforcement (CSQL-RLS-001)
-- app_write: DML access for application write operations (subject to RLS)
-- app_read: SELECT-only access for read replicas and reporting (subject to RLS)
--
-- The application login role should INHERIT from app_write (or app_read for read-only services).
-- Migrations run as superuser/owner (DATABASE_URL_ADMIN) which bypasses RLS.

-- Create roles if they don't exist (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_write') THEN
    CREATE ROLE app_write NOLOGIN;
    RAISE NOTICE 'Created role: app_write';
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_read') THEN
    CREATE ROLE app_read NOLOGIN;
    RAISE NOTICE 'Created role: app_read';
  END IF;
END
$$;

-- Grant schema USAGE to both roles
GRANT USAGE ON SCHEMA core TO app_write, app_read;
GRANT USAGE ON SCHEMA security TO app_write, app_read;
GRANT USAGE ON SCHEMA audit TO app_write, app_read;
GRANT USAGE ON SCHEMA hr TO app_write, app_read;
GRANT USAGE ON SCHEMA payroll TO app_write, app_read;
GRANT USAGE ON SCHEMA benefits TO app_write, app_read;
GRANT USAGE ON SCHEMA talent TO app_write, app_read;
GRANT USAGE ON SCHEMA learning TO app_write, app_read;
GRANT USAGE ON SCHEMA recruitment TO app_write, app_read;

-- Grant table permissions to app_write (full DML)
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA core TO app_write;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA security TO app_write;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA audit TO app_write;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA hr TO app_write;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA payroll TO app_write;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA benefits TO app_write;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA talent TO app_write;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA learning TO app_write;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA recruitment TO app_write;

-- Grant sequence usage to app_write (for IDENTITY columns)
GRANT USAGE ON ALL SEQUENCES IN SCHEMA core TO app_write;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA security TO app_write;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA audit TO app_write;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA hr TO app_write;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA payroll TO app_write;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA benefits TO app_write;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA talent TO app_write;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA learning TO app_write;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA recruitment TO app_write;

-- Grant table permissions to app_read (SELECT only)
GRANT SELECT ON ALL TABLES IN SCHEMA core TO app_read;
GRANT SELECT ON ALL TABLES IN SCHEMA security TO app_read;
GRANT SELECT ON ALL TABLES IN SCHEMA audit TO app_read;
GRANT SELECT ON ALL TABLES IN SCHEMA hr TO app_read;
GRANT SELECT ON ALL TABLES IN SCHEMA payroll TO app_read;
GRANT SELECT ON ALL TABLES IN SCHEMA benefits TO app_read;
GRANT SELECT ON ALL TABLES IN SCHEMA talent TO app_read;
GRANT SELECT ON ALL TABLES IN SCHEMA learning TO app_read;
GRANT SELECT ON ALL TABLES IN SCHEMA recruitment TO app_read;

-- Set default privileges for future tables (so new tables get the same grants)
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA security GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA payroll GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA benefits GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA talent GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA learning GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA recruitment GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_write;

ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT USAGE ON SEQUENCES TO app_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA security GRANT USAGE ON SEQUENCES TO app_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT USAGE ON SEQUENCES TO app_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr GRANT USAGE ON SEQUENCES TO app_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA payroll GRANT USAGE ON SEQUENCES TO app_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA benefits GRANT USAGE ON SEQUENCES TO app_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA talent GRANT USAGE ON SEQUENCES TO app_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA learning GRANT USAGE ON SEQUENCES TO app_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA recruitment GRANT USAGE ON SEQUENCES TO app_write;

ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT SELECT ON TABLES TO app_read;
ALTER DEFAULT PRIVILEGES IN SCHEMA security GRANT SELECT ON TABLES TO app_read;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT SELECT ON TABLES TO app_read;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr GRANT SELECT ON TABLES TO app_read;
ALTER DEFAULT PRIVILEGES IN SCHEMA payroll GRANT SELECT ON TABLES TO app_read;
ALTER DEFAULT PRIVILEGES IN SCHEMA benefits GRANT SELECT ON TABLES TO app_read;
ALTER DEFAULT PRIVILEGES IN SCHEMA talent GRANT SELECT ON TABLES TO app_read;
ALTER DEFAULT PRIVILEGES IN SCHEMA learning GRANT SELECT ON TABLES TO app_read;
ALTER DEFAULT PRIVILEGES IN SCHEMA recruitment GRANT SELECT ON TABLES TO app_read;
